language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO=1.4.15
  - DJANGO=1.6.7
  - DJANGO=1.7
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.4.15
    - python: "3.3"
      env: DJANGO=1.4.15
    - python: "3.4"
      env: DJANGO=1.4.15
    - python: "3.4"
      env: DJANGO=1.6.7
install:
  - pip install -q Django==$DJANGO
  - pip install -q django-nose==1.2 coverage coveralls flake8
  - pip install -e .
script:
  - flake8 account
  - coverage run runtests.py
after_script:
  - coveralls
